[messages]
message_count = 7_000_000
message_length = 100

[producer]
producer_count = 1
batch_size = 10

[sender]
sender_count = 5_000
send_time_mean = 0.1
send_time_stddev = 0.01

[monitor]
print_frequency = 2
